server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # configuração do CORS (p/ front)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        # ROTA 1: Login e Auth
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/login/**, /oauth2/**, /api/auth/**

        # ROTA 2: Agendamentos
        - id: agendamento-service
          uri: lb://AGENDAMENTO-SERVICE
          predicates:
            - Path=/api/bookings/**

        # ROTA 3: Pagamentos
        - id: pagamento-service
          uri: lb://PAGAMENTO-SERVICE
          predicates:
            - Path=/api/payments/**

        # ROTA 4: Agendamentos
        - id: barbershop-route
          uri: lb://AGENDAMENTO-SERVICE
          predicates:
            - Path=/api/barbershops/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/