server:
  port: 8082

spring:
  application:
    name: agendamento-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/barbearia_agenda

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: k@8b$Z!E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkY